import './styles.css';
import './pages/ui';
import './pages/garage/api_garage';
import './pages/garage/buttons_garage';
import './pages/garage/utils_garage';
import './pages/garage/drive_car';
import './pages/winners/api_winners';
import './pages/winners/buttons_winners';
import './score';
